[package]
name = "stl-rs"
version = "0.1.0"
authors = ["joseph dao <joedao55@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.4"
scan_fmt = "0.2.5"
